"""empty message

Revision ID: 00915ec79bb9
Revises: c30794def686
Create Date: 2018-02-09 10:31:41.911192

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '00915ec79bb9'
down_revision = 'c30794def686'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('banner', sa.Column('create_time', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('banner', 'create_time')
    # ### end Alembic commands ###
